### PR TITLE
[feat] add DeepInfra benchmarks

### PR DESCRIPTION
**Pull request by ovuruska**
Implemented DeepInfra Mixtral-8x22B, Mixtral 8x7B, Llama-3-70B and Llama-3-8B API metrics.

### CODE REVIEW

**Comment by ovuruska** [comment]
Hi @juberti, where should we insert DEEPINFRA_API_TOKEN?

**Comment by juberti** [comment]
You can send it to justin@fixie.ai and I'll configure it on our benchmark runners.

**Review by juberti — APPROVED** [review]

**Comment by ovuruska** [comment]
Thanks for the quick response @juberti. I'll post an API key in a while.

**Comment by ovuruska** [comment]
I sent the email @juberti

**Pull request merged**
